namespace: servas-app
helm:
  releaseName: traefik
  chart: https://github.com/traefik/traefik-helm-chart/archive/refs/tags/v35.2.0.tar.gz
targetCustomizations: 
  - name: hasIngressController
    doNotDeploy: true
    clusterSelector: 
      matchLabels: 
        name: local
