namespace: servas-app
helm:
  releaseName: traefik
  chart: traefik/traefik
  repo: oci://ghcr.io/traefik/helm/traefik
  version: 35.2.0
targetCustomizations: 
  - name: hasIngressController
    doNotDeploy: true
    clusterSelector: 
      matchLabels: 
        name: local
