apiVersion: v1
kind: Secret
namespace: {{ .Values.namespace }}
metadata:
  name: {{ .Values.secretName }}
data:
    {{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.secretName).data }}
    {{- if $secret.appKey }}

    appKey: {{ $secret.appKey }}
    mdbPW: {{ $secret.mdbPW }}
    mdbRoot: {{ $secret.mdbRoot }}

    {{ else }}
    appKey: {{ randAlphaNum 32 | b64enc }}
    mdbPW: {{ randAlphaNum 16 | b64enc }}
    mdbRoot: {{ randAlphaNum 16 | b64enc }}

  {{- end }}
    