apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servas-helm.fullname" . }}
  labels:
    {{- include "servas-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
    spec:
      selector: 
        matchLabels: 
          {{- include "servas-helm.labels" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
          - name: APP_NAME
            value: {{ .Values.Servas.appName }}
          - name: APP_ENV
            value: {{ .Values.Servas.appEnv }}
          - name: APP_DEBUG
            value: {{ .Values.Servas.appDebug }}
          - name: APP_URL
            value: {{ .Values.Servas.appURL }}
          - name: SERVAS_ENABLE_REGISTRATION
            value: {{ .Values.Servas.appRegistration }}
          - name: SERVAS_SHOW_APP_VERSION
            value: {{ .Values.Servas.showVersion }}
          - name: MARIADB_USER
            value: {{ .Values.Servas.dbUserName }}
          - name: MARIADB_DATABASE
            value: {{ .Values.Servas.dbName }}
          - name: APP_KEY
            valueFrom: 
              secretKeyRef:
                name: {{ .Values.Servas.secretName }}
                key: appKey
          - name: MARIADB_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: {{ .Values.Servas.secretName }}
                key: mdbRoot
          - name: MARIADB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: {{ .Values.Servas.secretName }}
                key: mdbPW
          ports:
            - name: servasPort
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          {{- with .Values.volumeMounts }}
#          volumeMounts:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#      {{- with .Values.volumes }}
#      volumes:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
