apiVersion: v1
kind: Service
metadata:
  name: {{ include "servas-helm.fullname" . }}
  labels:
    {{- include "servas-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: servasPort
      protocol: TCP
      name: servasPort
  selector:
    {{- include "servas-helm.selectorLabels" . | nindent 4 }}